notifications:
  email: false
language: shell

env:
  - NUMPY_BUILD_VERSION=1.10.4

jobs:
  include:
    # linux build
    - services: docker
      language: python
      env:
        - PYTHON=python3
        - CIBW_BEFORE_BUILD="pip install Cython numpy==$NUMPY_BUILD_VERSION"
    # macos build
    - os: osx
      env:
        - PYTHON=python3
        - CIBW_BEFORE_BUILD="pip install Cython numpy==$NUMPY_BUILD_VERSION"
    # win_amd64 build
    - os: windows
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
      env:
        - CIBW_BUILD="*-win_amd64"
        - PLATFORM_OPTION="-A x64"
        - PYTHON=/c/Python38/python.exe
        - CIBW_BEFORE_BUILD="pip install numpy==$NUMPY_BUILD_VERSION; bash build.sh"
    # win32 build
    - os: windows
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
      env:
        - CIBW_BUILD="*-win32"
        - PYTHON=/c/Python38/python.exe
        - CIBW_BEFORE_BUILD="pip install numpy==$NUMPY_BUILD_VERSION; bash build.sh"
    - language: python
      arch: arm64
      install:
      script:
        # without --no-cache:
        # [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/'
        - python3 -m pip install -U --no-cache setuptools pip wheel Cython "numpy==$NUMPY_BUILD_VERSION"
        - python3 -m pip install flake8 codecov
        - flake8
        - python3 setup.py sdist
        - python3 -m pip install --no-cache dist/*.tar.gz
        - rm -rf pydivsufsort # https://github.com/nedbat/coveragepy/issues/971
        - coverage run -m pytest tests
      after_success:
        - codecov
        - |
          if [[ $TWINE_PASSWORD  ]]; then
            python3 -m pip install --no-cache twine
            python3 -m twine upload --skip-existing dist/*
          fi

env:
  global:
    - TWINE_USERNAME=__token__
    - CIBW_SKIP="cp27-* cp35-* pp*"
    - CIBW_TEST_REQUIRES=pytest
    - CIBW_TEST_COMMAND="pytest {project}"

install:
  - $PYTHON -m pip install cibuildwheel

script:
  - $PYTHON -m cibuildwheel --output-dir wheelhouse
  - ls wheelhouse

after_success:
  - |
    if [[ $TWINE_PASSWORD  ]]; then
      $PYTHON -m pip install twine
      $PYTHON -m twine upload --skip-existing wheelhouse/*.whl
    fi
