name: Test and Build
on:
    - push
    - pull_request
jobs:
    testing:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        steps:
            - name: Checkout Repository And Submodules
              uses: actions/checkout@v2
              with:
                  submodules: recursive
            - name: Set Up Python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Display Python Version
              run: python -c "import sys; print(sys.version)"
              shell: bash
            - name: Install Pydivsufsort And Other Dependencies
              run: |
                  python -m pip install pytest flake8
                  bash ./cibw_before_build.sh
                  python -m pip install . -v
              shell: bash
            - name: Run Flake8
              run: flake8 .
              shell: bash
            - name: Run Unit Tests
              run: |
                  pytest tests
              shell: bash
